package com.pcis.smartbus.db.dao;

import com.pcis.smartbus.db.domain.DataPoint;
import com.pcis.smartbus.db.domain.DataPointExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DataPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_point
     *
     * @mbg.generated
     */
    long countByExample(DataPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_point
     *
     * @mbg.generated
     */
    int deleteByExample(DataPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_point
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_point
     *
     * @mbg.generated
     */
    int insert(DataPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_point
     *
     * @mbg.generated
     */
    int insertSelective(DataPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_point
     *
     * @mbg.generated
     */
    DataPoint selectOneByExample(DataPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_point
     *
     * @mbg.generated
     */
    DataPoint selectOneByExampleSelective(@Param("example") DataPointExample example, @Param("selective") DataPoint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_point
     *
     * @mbg.generated
     */
    List<DataPoint> selectByExampleSelective(@Param("example") DataPointExample example, @Param("selective") DataPoint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_point
     *
     * @mbg.generated
     */
    List<DataPoint> selectByExample(DataPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_point
     *
     * @mbg.generated
     */
    DataPoint selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") DataPoint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_point
     *
     * @mbg.generated
     */
    DataPoint selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_point
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DataPoint record, @Param("example") DataPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_point
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DataPoint record, @Param("example") DataPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_point
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DataPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_point
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DataPoint record);
}