package com.pcis.smartbus.db.dao;

import com.pcis.smartbus.db.domain.ProjectUserRelation;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ProjectUserRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user_relation
     *
     * @mbg.generated
     */
    int insert(ProjectUserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user_relation
     *
     * @mbg.generated
     */
    int insertSelective(ProjectUserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user_relation
     *
     * @mbg.generated
     */
    ProjectUserRelation selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ProjectUserRelation.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user_relation
     *
     * @mbg.generated
     */
    ProjectUserRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProjectUserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProjectUserRelation record);
}