package com.pcis.smartbus.db.dao;

import com.pcis.smartbus.db.domain.ReportForm;
import com.pcis.smartbus.db.domain.ReportFormExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReportFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_form
     *
     * @mbg.generated
     */
    long countByExample(ReportFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_form
     *
     * @mbg.generated
     */
    int deleteByExample(ReportFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_form
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_form
     *
     * @mbg.generated
     */
    int insert(ReportForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_form
     *
     * @mbg.generated
     */
    int insertSelective(ReportForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_form
     *
     * @mbg.generated
     */
    ReportForm selectOneByExample(ReportFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_form
     *
     * @mbg.generated
     */
    ReportForm selectOneByExampleSelective(@Param("example") ReportFormExample example, @Param("selective") ReportForm.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_form
     *
     * @mbg.generated
     */
    List<ReportForm> selectByExampleSelective(@Param("example") ReportFormExample example, @Param("selective") ReportForm.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_form
     *
     * @mbg.generated
     */
    List<ReportForm> selectByExample(ReportFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_form
     *
     * @mbg.generated
     */
    ReportForm selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") ReportForm.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_form
     *
     * @mbg.generated
     */
    ReportForm selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_form
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ReportForm record, @Param("example") ReportFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_form
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ReportForm record, @Param("example") ReportFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_form
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReportForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_form
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReportForm record);
}