package com.pcis.smartbus.db.dao;

import com.pcis.smartbus.db.domain.SmartbusUser;
import com.pcis.smartbus.db.domain.SmartbusUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmartbusUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smartbus_user
     *
     * @mbg.generated
     */
    long countByExample(SmartbusUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smartbus_user
     *
     * @mbg.generated
     */
    int deleteByExample(SmartbusUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smartbus_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smartbus_user
     *
     * @mbg.generated
     */
    int insert(SmartbusUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smartbus_user
     *
     * @mbg.generated
     */
    int insertSelective(SmartbusUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smartbus_user
     *
     * @mbg.generated
     */
    SmartbusUser selectOneByExample(SmartbusUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smartbus_user
     *
     * @mbg.generated
     */
    SmartbusUser selectOneByExampleSelective(@Param("example") SmartbusUserExample example, @Param("selective") SmartbusUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smartbus_user
     *
     * @mbg.generated
     */
    List<SmartbusUser> selectByExampleSelective(@Param("example") SmartbusUserExample example, @Param("selective") SmartbusUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smartbus_user
     *
     * @mbg.generated
     */
    List<SmartbusUser> selectByExample(SmartbusUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smartbus_user
     *
     * @mbg.generated
     */
    SmartbusUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SmartbusUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smartbus_user
     *
     * @mbg.generated
     */
    SmartbusUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smartbus_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SmartbusUser record, @Param("example") SmartbusUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smartbus_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SmartbusUser record, @Param("example") SmartbusUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smartbus_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmartbusUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smartbus_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmartbusUser record);

    //This is wrote by hand.
    SmartbusUser selectByUserName(String userName);

    Integer getUserNum();

    List<SmartbusUser> getAPageUserDesc(int startNo, int pageSize, String sortBy);
    List<SmartbusUser> getAPageUserAsc(int startNo, int pageSize, String sortBy);
    List<SmartbusUser> getAPageUser(int startNo, int pageSize, String sortBy, String direction);

    List<SmartbusUser> getAPageUserByNameSearch(int startNo, int pageSize, String sortBy, String direction, String searchContent);
    List<SmartbusUser> getAPageUserByCapacity(int startNo, int pageSize, String sortBy, String direction, int capacity);
    List<SmartbusUser> getAPageUserByCompanySearch(int startNo, int pageSize, String sortBy, String direction, String searchContent);

    Integer getUserNumByNameSearch(String searchContent);
    Integer getUserNumByCapacity(int capacity);
    Integer getUserNumByCompanySearch(String searchContent);




}