package com.pcis.smartbus.db.dao;

import com.pcis.smartbus.db.domain.WTAdmin;
import org.apache.ibatis.annotations.Param;

public interface WTAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_admin
     *
     * @mbg.generated
     */
    int insert(WTAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_admin
     *
     * @mbg.generated
     */
    int insertSelective(WTAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_admin
     *
     * @mbg.generated
     */
    WTAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") WTAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_admin
     *
     * @mbg.generated
     */
    WTAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WTAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WTAdmin record);
}