package com.pcis.smartbus.db.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class DataPoint {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_point.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_point.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_point.place
     *
     * @mbg.generated
     */
    private String place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_point.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_point.upper_bound
     *
     * @mbg.generated
     */
    private Float upperBound;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_point.lower_bound
     *
     * @mbg.generated
     */
    private Float lowerBound;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_point.sender_mac
     *
     * @mbg.generated
     */
    private String senderMac;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_point.id
     *
     * @return the value of data_point.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_point.id
     *
     * @param id the value for data_point.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_point.name
     *
     * @return the value of data_point.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_point.name
     *
     * @param name the value for data_point.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_point.place
     *
     * @return the value of data_point.place
     *
     * @mbg.generated
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_point.place
     *
     * @param place the value for data_point.place
     *
     * @mbg.generated
     */
    public void setPlace(String place) {
        this.place = place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_point.unit
     *
     * @return the value of data_point.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_point.unit
     *
     * @param unit the value for data_point.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_point.upper_bound
     *
     * @return the value of data_point.upper_bound
     *
     * @mbg.generated
     */
    public Float getUpperBound() {
        return upperBound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_point.upper_bound
     *
     * @param upperBound the value for data_point.upper_bound
     *
     * @mbg.generated
     */
    public void setUpperBound(Float upperBound) {
        this.upperBound = upperBound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_point.lower_bound
     *
     * @return the value of data_point.lower_bound
     *
     * @mbg.generated
     */
    public Float getLowerBound() {
        return lowerBound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_point.lower_bound
     *
     * @param lowerBound the value for data_point.lower_bound
     *
     * @mbg.generated
     */
    public void setLowerBound(Float lowerBound) {
        this.lowerBound = lowerBound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_point.sender_mac
     *
     * @return the value of data_point.sender_mac
     *
     * @mbg.generated
     */
    public String getSenderMac() {
        return senderMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_point.sender_mac
     *
     * @param senderMac the value for data_point.sender_mac
     *
     * @mbg.generated
     */
    public void setSenderMac(String senderMac) {
        this.senderMac = senderMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_point
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", place=").append(place);
        sb.append(", unit=").append(unit);
        sb.append(", upperBound=").append(upperBound);
        sb.append(", lowerBound=").append(lowerBound);
        sb.append(", senderMac=").append(senderMac);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_point
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DataPoint other = (DataPoint) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getPlace() == null ? other.getPlace() == null : this.getPlace().equals(other.getPlace()))
            && (this.getUnit() == null ? other.getUnit() == null : this.getUnit().equals(other.getUnit()))
            && (this.getUpperBound() == null ? other.getUpperBound() == null : this.getUpperBound().equals(other.getUpperBound()))
            && (this.getLowerBound() == null ? other.getLowerBound() == null : this.getLowerBound().equals(other.getLowerBound()))
            && (this.getSenderMac() == null ? other.getSenderMac() == null : this.getSenderMac().equals(other.getSenderMac()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_point
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPlace() == null) ? 0 : getPlace().hashCode());
        result = prime * result + ((getUnit() == null) ? 0 : getUnit().hashCode());
        result = prime * result + ((getUpperBound() == null) ? 0 : getUpperBound().hashCode());
        result = prime * result + ((getLowerBound() == null) ? 0 : getLowerBound().hashCode());
        result = prime * result + ((getSenderMac() == null) ? 0 : getSenderMac().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table data_point
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "VARCHAR", false),
        name("name", "name", "VARCHAR", true),
        place("place", "place", "VARCHAR", false),
        unit("unit", "unit", "VARCHAR", false),
        upperBound("upper_bound", "upperBound", "REAL", false),
        lowerBound("lower_bound", "lowerBound", "REAL", false),
        senderMac("sender_mac", "senderMac", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table data_point
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table data_point
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table data_point
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table data_point
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table data_point
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table data_point
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table data_point
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table data_point
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table data_point
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table data_point
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table data_point
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table data_point
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table data_point
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table data_point
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table data_point
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table data_point
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}