package com.pcis.smartbus.db.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class WTAdmin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wt_admin.id
     *
     * @mbg.generated
     */
    private Integer id;


    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smartbus_user.real_name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wt_admin.pwd
     *
     * @mbg.generated
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wt_admin.real_name
     *
     * @mbg.generated
     */

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wt_admin.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wt_admin.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wt_admin.company
     *
     * @mbg.generated
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smartbus_user.capacity
     *
     * @mbg.generated
     */
    private Integer capacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smartbus_user.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smartbus_user.alarm_mail
     *
     * @mbg.generated
     */
    private Boolean alarmMail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smartbus_user.alarm_sms
     *
     * @mbg.generated
     */
    private Boolean alarmSms;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wt_admin.id
     *
     * @return the value of wt_admin.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wt_admin.id
     *
     * @param id the value for wt_admin.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }


    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smartbus_user.real_name
     *
     * @return the value of smartbus_user.real_name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smartbus_user.real_name
     *
     * @param realName the value for smartbus_user.real_name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wt_admin.pwd
     *
     * @return the value of wt_admin.pwd
     *
     * @mbg.generated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wt_admin.pwd
     *
     * @param pwd the value for wt_admin.pwd
     *
     * @mbg.generated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }



 
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wt_admin.email
     *
     * @return the value of wt_admin.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wt_admin.email
     *
     * @param email the value for wt_admin.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wt_admin.phone
     *
     * @return the value of wt_admin.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wt_admin.phone
     *
     * @param phone the value for wt_admin.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wt_admin.company
     *
     * @return the value of wt_admin.company
     *
     * @mbg.generated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wt_admin.company
     *
     * @param company the value for wt_admin.company
     *
     * @mbg.generated
     */
    public void setCompany(String company) {
        this.company = company;
    }

  
    public Integer getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smartbus_user.capacity
     *
     * @param capacity the value for smartbus_user.capacity
     *
     * @mbg.generated
     */
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smartbus_user.company_id
     *
     * @return the value of smartbus_user.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smartbus_user.company_id
     *
     * @param companyId the value for smartbus_user.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smartbus_user.alarm_mail
     *
     * @return the value of smartbus_user.alarm_mail
     *
     * @mbg.generated
     */
    public Boolean getAlarmMail() {
        return alarmMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smartbus_user.alarm_mail
     *
     * @param alarmMail the value for smartbus_user.alarm_mail
     *
     * @mbg.generated
     */
    public void setAlarmMail(Boolean alarmMail) {
        this.alarmMail = alarmMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smartbus_user.alarm_sms
     *
     * @return the value of smartbus_user.alarm_sms
     *
     * @mbg.generated
     */
    public Boolean getAlarmSms() {
        return alarmSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smartbus_user.alarm_sms
     *
     * @param alarmSms the value for smartbus_user.alarm_sms
     *
     * @mbg.generated
     */
    public void setAlarmSms(Boolean alarmSms) {
        this.alarmSms = alarmSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smartbus_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userName=").append(userName);
        sb.append(", realName=").append(realName);
        sb.append(", password=").append(password);
        sb.append(", phone=").append(phone);
        sb.append(", email=").append(email);
        sb.append(", created=").append(created);
        sb.append(", updated=").append(updated);
        sb.append(", capacity=").append(capacity);
        sb.append(", companyId=").append(companyId);
        sb.append(", alarmMail=").append(alarmMail);
        sb.append(", alarmSms=").append(alarmSms);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_admin
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WTAdmin other = (WTAdmin) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getRealName() == null ? other.getRealName() == null : this.getRealName().equals(other.getRealName()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getCreated() == null ? other.getCreated() == null : this.getCreated().equals(other.getCreated()))
            && (this.getUpdated() == null ? other.getUpdated() == null : this.getUpdated().equals(other.getUpdated()))
            && (this.getCapacity() == null ? other.getCapacity() == null : this.getCapacity().equals(other.getCapacity()))
            && (this.getCompanyId() == null ? other.getCompanyId() == null : this.getCompanyId().equals(other.getCompanyId()))
            && (this.getAlarmMail() == null ? other.getAlarmMail() == null : this.getAlarmMail().equals(other.getAlarmMail()))
            && (this.getAlarmSms() == null ? other.getAlarmSms() == null : this.getAlarmSms().equals(other.getAlarmSms()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_admin
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getRealName() == null) ? 0 : getRealName().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getCreated() == null) ? 0 : getCreated().hashCode());
        result = prime * result + ((getUpdated() == null) ? 0 : getUpdated().hashCode());
        result = prime * result + ((getCapacity() == null) ? 0 : getCapacity().hashCode());
        result = prime * result + ((getCompanyId() == null) ? 0 : getCompanyId().hashCode());
        result = prime * result + ((getAlarmMail() == null) ? 0 : getAlarmMail().hashCode());
        result = prime * result + ((getAlarmSms() == null) ? 0 : getAlarmSms().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table wt_admin
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        userName("user_name", "userName", "VARCHAR", false),
        realName("real_name", "realName", "VARCHAR", false),
        password("password", "password", "VARCHAR", true),
        phone("phone", "phone", "VARCHAR", false),
        email("email", "email", "VARCHAR", false),
        created("created", "created", "TIMESTAMP", false),
        updated("updated", "updated", "TIMESTAMP", false),
        capacity("capacity", "capacity", "INTEGER", false),
        companyId("company_id", "companyId", "INTEGER", false),
        alarmMail("alarm_mail", "alarmMail", "BIT", false),
        alarmSms("alarm_sms", "alarmSms", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table wt_admin
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table wt_admin
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table wt_admin
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table wt_admin
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table wt_admin
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table wt_admin
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table wt_admin
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table wt_admin
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table wt_admin
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table wt_admin
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table wt_admin
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table wt_admin
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table wt_admin
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table wt_admin
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table wt_admin
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table wt_admin
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}